import { USER_TEAM_FLAG, USER_TEAM_NAME } from "@/data/teams";

// Flag emoji for every nation that appears in the WC squad data (1982–2022),
// plus historical sides (West Germany, Soviet Union, Yugoslavia, …).
const FLAGS: Record<string, string> = {
  Algeria: "🇩🇿",
  Angola: "🇦🇴",
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Bolivia: "🇧🇴",
  "Bosnia and Herzegovina": "🇧🇦",
  Brazil: "🇧🇷",
  Bulgaria: "🇧🇬",
  Cameroon: "🇨🇲",
  Canada: "🇨🇦",
  Chile: "🇨🇱",
  China: "🇨🇳",
  Colombia: "🇨🇴",
  "Costa Rica": "🇨🇷",
  Croatia: "🇭🇷",
  "Czech Republic": "🇨🇿",
  Czechoslovakia: "🇨🇿",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  "El Salvador": "🇸🇻",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Greece: "🇬🇷",
  Honduras: "🇭🇳",
  Hungary: "🇭🇺",
  Iceland: "🇮🇸",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Italy: "🇮🇹",
  "Ivory Coast": "🇨🇮",
  Jamaica: "🇯🇲",
  Japan: "🇯🇵",
  Kuwait: "🇰🇼",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  "New Zealand": "🇳🇿",
  Nigeria: "🇳🇬",
  "North Korea": "🇰🇵",
  "Northern Ireland": "🇬🇧",
  Norway: "🇳🇴",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  "Republic of Ireland": "🇮🇪",
  Ireland: "🇮🇪",
  Romania: "🇷🇴",
  Russia: "🇷🇺",
  "Saudi Arabia": "🇸🇦",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  "Serbia and Montenegro": "🇷🇸",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "Soviet Union": "🇷🇺",
  Spain: "🇪🇸",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Togo: "🇹🇬",
  "Trinidad and Tobago": "🇹🇹",
  Tunisia: "🇹🇳",
  Turkey: "🇹🇷",
  Ukraine: "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  "United States": "🇺🇸",
  Uruguay: "🇺🇾",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "West Germany": "🇩🇪",
  Yugoslavia: "🇷🇸",
};

/** Flag for a nation by name. */
export function flagFor(team: string): string {
  return FLAGS[team] ?? "🏳️";
}

/** Flag for a team in the simulated tournament (user team + nations). */
export function teamFlag(name: string): string {
  if (name === USER_TEAM_NAME) return USER_TEAM_FLAG;
  return FLAGS[name] ?? "🏳️";
}
